### github-action-variable-03.yml

name: Test Github Actions variable-03
run-name: Run Github Actions var, secret
on:
  workflow_dispatch

jobs:
  check-vars-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello, Var_Test"
      ### 깃헙에 생성한 밸류값 쓰기
        run: echo "Hello, ${{ vars.VAR_TEST }}"

  check-sevret-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello, SECRET_TEST"
      ### 깃헙에 생성한 시크릿값 쓰기
        run: echo "Hello, ${{ secrets.SECRET_TEST }}"
