### github-action-variable-01.yml

name: Test Github Actions variable-01

on:
  workflow_dispatch

env: 
  DAY_OF_WEEK: Friday

jobs:
  check-var:
    runs-on: ubuntu-latest
    env:
      MESSAGE: Hello
    steps:
      - name: "It's Day!"
        if: ${{ env.DAY_OF_WEEK == 'Friday' }}
        run: echo "$MESSAGE, Today is $DAY_OF_WEEK!"

  check-var2:
    runs-on: ubuntu-latest
    env:
      MESSAGE: Hello
    steps:
      - name: "It's Day!"
        run: echo "$MESSAGE, Today is $DAY_OF_WEEK!"

  check-var3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [Apple, Banana, Kiwi]
    steps:
      - name: "It's fruits!"
        run: echo "Hello, ${{ matrix.fruit }}"

  check-var4:
    runs-on: ubuntu-latest
    steps:
      - name: "It's fruits!"
        run: |
          for fruit in Apple Banana Kiwi; do
            echo "hello, $fruit!"
          done
